typography_spectrum: 0.4233794699195256
content_rating:
  adult: false
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.17165472376980995
  lightness: 0.11928877181567178
  saturation: 0.9804279194584135
  rhythmicContrast: 0.3912778010551292
github: true
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.7815021099819627
analytics:
  google: UA-1762611-3
  facebook: null
  twitter: null
author:
  name: Ryan Marrs
  email: rmarrs@ryanmarrs.com
  url: 'http://ryanmarrs.com'
name: Ryan Marrs
url: 'http://ryanmarrs.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: YouTube
    url: 'http://youtube.com/rmarrsmi'
    type: external
favicon: null
title: Ryan Marrs
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8de3dc3c-b6db-48cf-a185-647cf67cd7af.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8de3dc3c-b6db-48cf-a185-647cf67cd7af.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: A place for my thoughts
purpose:
  - type: contact
    url: 'mailto:rmarrs@ryanmarrs.com'
    label: Email Me
