name: RyanMarrs
favicon: null
layout_spectrum: 0.893368820194155
typography_spectrum: 0.42746994318440557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1762611-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22050411417149007
  lightness: 0.12386880978010595
  saturation: 0.2746954506728798
  rhythmicContrast: 0.4215372009202838
purpose:
  - type: contact
    url: 'mailto:rmarrs@ryanmarrs.com'
    label: Contact me
content: []
content_rating:
  adult: false
author:
  name: Ryan Marrs
  email: rmarrs@gmail.com
  url: 'http://ryanmarrs.com'
url: 'https://ryanmarrs.com'
title: Ryan Marrs
description: A place for my thoughts
github: true
